---
- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  collections:
    - community.general

  tasks:
    - name: Install required brew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - wezterm
        - vim
        - git
        - tmux
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting
        - eza
        - fzf

    - name: Install required fonts
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - font-fira-code-nerd-font
        - font-go-mono-nerd-font
        - font-hack-nerd-font
        - font-jetbrains-mono-nerd-font
        - font-meslo-lg-nerd-font
        - font-monaspace-nerd-font
        - font-noto-sans-symbols-2

    - name: Copy WezTerm config
      copy:
        src: files/.wezterm.lua
        dest: ~/.wezterm.lua
        mode: 0644

    - name: Copy Tmux config
      copy:
        src: files/.tmux.conf
        dest: ~/.tmux.conf
        mode: 0644

    - name: Ensure ~/.config directory exists
      file:
        path: ~/.config
        state: directory
        mode: '0755'

    - name: Copy Starship config
      copy:
        src: files/starship.toml
        dest: ~/.config/starship.toml
        mode: 0644

    - name: Copy Vim config
      copy:
        src: files/.vimrc
        dest: ~/.vimrc
        mode: 0644