---
- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  collections:
    - community.general

  tasks:
    # Corriger les permissions sur /private/tmp
    - name: Fix permissions on /private/tmp
      become: true
      file:
        path: /private/tmp
        mode: '1777'
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "wheel"

    # Supprimer l'ancien socket de tmux s'il existe
    - name: Remove tmux socket if it exists
      file:
        path: /private/tmp/tmux-501
        state: absent
      ignore_errors: true

    # Démarrer une session tmux pour forcer la création du socket
    - name: Start a dummy tmux session to create the socket
      command: /opt/homebrew/bin/tmux new-session -d -s dummy_session

    # Démarrer le serveur tmux manuellement (si nécessaire)
    - name: Start tmux server manually
      command: /opt/homebrew/bin/tmux start-server

    # Ajouter le tap pour SF Mono Nerd Font Ligaturized
    - name: Add homebrew tap for SFMono Nerd Font Ligaturized
      community.general.homebrew_tap:
        name: shaunsingh/sfmono-nerd-font-ligaturized
        state: present

    # # Installer les packages Homebrew nécessaires
    # - name: Install required brew packages
    #   community.general.homebrew:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - wezterm
    #     - vim
    #     - git
    #     - tmux
    #     - zsh
    #     - zsh-autosuggestions
    #     - zsh-completions
    #     - zsh-syntax-highlighting
    #     - eza
    #     - fzf
    #     - starship
    #     - zoxide
    #     - thefuck

    # # Installer les polices requises
    # - name: Install required fonts
    #   community.general.homebrew:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - font-fira-code-nerd-font
    #     - font-go-mono-nerd-font
    #     - font-hack-nerd-font
    #     - font-jetbrains-mono-nerd-font
    #     - font-meslo-lg-nerd-font
    #     - font-monaspace-nerd-font
    #     - font-noto-sans-symbols-2
    #     - font-sf-mono-nerd-font-ligaturized

    # Installer TPM (Tmux Plugin Manager)
    - name: Clone TPM (Tmux Plugin Manager)
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    # Copier les configurations de Tmux
    - name: Copy Tmux config
      copy:
        src: files/.tmux.conf
        dest: ~/.tmux.conf
        mode: 0644
        force: true

    # Vérifier que la session tpm_install existe
    - name: Check if tmux session tpm_install is running
      command: /opt/homebrew/bin/tmux ls
      register: tmux_sessions
      ignore_errors: yes

    # Installer les plugins TPM si la session tpm_install est active
    - name: Install TPM plugins
      command: /bin/bash -lc '/opt/homebrew/bin/tmux new-session -d -s tpm_install && sleep 5 && /opt/homebrew/bin/tmux run-shell ~/.tmux/plugins/tpm/bin/install_plugins && /opt/homebrew/bin/tmux kill-session -t tpm_install'
      when: "'tpm_install' not in tmux_sessions.stdout"

    # Assurer que le répertoire ~/.config existe
    - name: Ensure ~/.config directory exists
      file:
        path: ~/.config
        state: directory
        mode: '0755'

    # Copier les configurations de WezTerm
    - name: Copy WezTerm config
      copy:
        src: files/.wezterm.lua
        dest: ~/.wezterm.lua
        mode: 0644
        force: true

    # Copier la configuration de Starship
    - name: Copy Starship config
      copy:
        src: files/starship.toml
        dest: ~/.config/starship.toml
        mode: 0644
        force: true

    # Copier la configuration de Vim
    - name: Copy Vim config
      copy:
        src: files/.vimrc
        dest: ~/.vimrc
        mode: 0644
        force: true

    # Copier la configuration de zshrc
    - name: Copy Vim config
      copy:
        src: files/.zshrc
        dest: ~/.zshrc
        mode: 0644
        force: true