---
- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  collections:
    - community.general

  tasks:

    # Add the tap for SF Mono Nerd Font Ligaturized
    - name: Add homebrew tap for SFMono Nerd Font Ligaturized
      community.general.homebrew_tap:
        name: shaunsingh/sfmono-nerd-font-ligaturized
        state: present

    # Install the required Homebrew packages
    - name: Install required brew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - wezterm
        - vim
        - git
        - tmux
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting
        - eza
        - fzf
        - starship
        - zoxide
        - thefuck

    # Install the required fonts
    - name: Install required fonts
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - font-fira-code-nerd-font
        - font-go-mono-nerd-font
        - font-hack-nerd-font
        - font-jetbrains-mono-nerd-font
        - font-meslo-lg-nerd-font
        - font-monaspace-nerd-font
        - font-noto-sans-symbols-2
        - font-sf-mono-nerd-font-ligaturized

    # Fix permissions on /private/tmp
    - name: Fix permissions on /private/tmp
      become: true
      file:
        path: /private/tmp
        mode: '1777'
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "wheel"

    # Remove the old tmux socket if it exists
    - name: Remove tmux socket if it exists
      file:
        path: /private/tmp/tmux-501
        state: absent
      ignore_errors: true

    # Start a tmux session to force socket creation
    - name: Start a dummy tmux session to create the socket
      command: /opt/homebrew/bin/tmux new-session -d -s dummy_session

    # Start tmux server manually (if needed)
    - name: Start tmux server manually
      command: /opt/homebrew/bin/tmux start-server

    # Install TPM (Tmux Plugin Manager)
    - name: Clone TPM (Tmux Plugin Manager)
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    # Copy Tmux configuration
    - name: Copy Tmux config
      copy:
        src: files/.tmux.conf
        dest: ~/.tmux.conf
        mode: 0644
        force: true

    # Check if the tpm_install session is running
    - name: Check if tmux session tpm_install is running
      command: /opt/homebrew/bin/tmux ls
      register: tmux_sessions
      ignore_errors: yes

    # Install TPM plugins if the tpm_install session is active
    - name: Install TPM plugins
      command: /bin/bash -lc '/opt/homebrew/bin/tmux new-session -d -s tpm_install && sleep 5 && /opt/homebrew/bin/tmux run-shell ~/.tmux/plugins/tpm/bin/install_plugins && /opt/homebrew/bin/tmux kill-session -t tpm_install'
      when: "'tpm_install' not in tmux_sessions.stdout"

    # Ensure the ~/.config directory exists
    - name: Ensure ~/.config directory exists
      file:
        path: ~/.config
        state: directory
        mode: '0755'

    # Copy WezTerm configuration
    - name: Copy WezTerm config
      copy:
        src: files/.wezterm.lua
        dest: ~/.wezterm.lua
        mode: 0644
        force: true

    # Copy Starship configuration
    - name: Copy Starship config
      copy:
        src: files/starship.toml
        dest: ~/.config/starship.toml
        mode: 0644
        force: true

    # Copy Vim configuration
    - name: Copy Vim config
      copy:
        src: files/.vimrc
        dest: ~/.vimrc
        mode: 0644
        force: true

    # Copy zshrc configuration
    - name: Copy zshrc config
      copy:
        src: files/.zshrc
        dest: ~/.zshrc
        mode: 0644
        force: true