- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  collections:
    - community.general

  tasks:
    # Installer les packages Homebrew nécessaires
    - name: Install required brew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - wezterm
        - vim
        - git
        - tmux
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting
        - eza
        - fzf
        - starship
        - zoxide
        - thefuck

    # Supprimer l'ancien répertoire du plugin s'il existe
    - name: Remove existing history-substring-search directory if it exists
      file:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/history-substring-search"
        state: absent

    # Cloner le plugin history-substring-search
    - name: Clone history-substring-search plugin
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/history-substring-search"

    # Assurer que le répertoire ~/.config existe
    - name: Ensure ~/.config directory exists
      file:
        path: ~/.config
        state: directory
        mode: '0755'

    # Copier les configurations
    - name: Copy WezTerm config
      copy:
        src: files/.wezterm.lua
        dest: ~/.wezterm.lua
        mode: 0644

    - name: Copy Tmux config
      copy:
        src: files/.tmux.conf
        dest: ~/.tmux.conf
        mode: 0644

    - name: Copy Starship config
      copy:
        src: files/starship.toml
        dest: ~/.config/starship.toml
        mode: 0644

    - name: Copy Vim config
      copy:
        src: files/.vimrc
        dest: ~/.vimrc
        mode: 0644

    - name: Copy Zsh config
      copy:
        src: files/.zshrc
        dest: ~/.zshrc
        mode: 0644